name: ZAP Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan de Vulnerabilidades (OWASP ZAP)
    steps:
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v4

      - name: 2. Configurar o ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Instalar dependências e subir a aplicação
        run: |
          npm install express
          # Inicia a aplicação em background (&)
          node server.js &
          # Espera 10 segundos para garantir que o servidor subiu
          sleep 10

      - name: 4. Executar OWASP ZAP CLI (Scan Ativo)
        run: |
          chmod 777 .
          # Trocamos para o zap-full-scan.py para ele "atacar" o formulário e achar o XSS
          docker run --network host -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://localhost:8080 -r zap-report.html

      - name: 5. Salvar Relatório ZAP como Artefato
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap-report.html